server.port=8080

spring.datasource.url=jdbc:postgresql://ep-misty-bread-att5tuu9.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_loZ36EBKGFwS
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.admin.default-username=admin
app.admin.default-password=admin123
app.cors.allowed-origins=https://mohan-portfolio-1.onrender.com